### ISSUE TITLE
[request] MTX44 from LRS method

### ISSUE THREAD

**Issue by Tcll** [adamlwgriffiths/Pyrr#25]
Loc,Rot,Sca = LRS # [ [0.,0.,0.], [0.,0.,0.], [1.,1.,1.] ]
    pyrr.matrix44.from_transforms( np.array( Loc+Rot+Sca ) )

If this is already available under another name, I'd like to request it listed in the docs. :)

**Comment by adamlwgriffiths** [comment]
I assume Rot is a set of eulers for roll, pitch, yaw.
There are functions for doing this, but it isn't a single step.

```
l,r,s = [ [0.,0.,0.], [0.,0.,0.], [1.,1.,1.] ]
mt = pyrr.matrix44.create_from_translation(l)
mr = pyrr.matrix44.create_from_eulers(r)
ms = pyrr.matrix44.create_from_scale(s)
# m = ms * mr * mt
m = pyrr.matrix44.multiply(ms, pyrr.matrix44.multiply(mr, mt))
```

Alternatively you can use the OO interface which makes the code more readable.
```
from pyrr import Matrix44
l,r,s = [ [0.,0.,0.], [0.,0.,0.], [1.,1.,1.] ]
mt = Matrix44.from_translation(l)
mr = Matrix44.from_eulers(r)
ms = Matrix44.from_scale(s)
m = ms * mr * mt
```

It could be trivially wrapped into a function.
I'm happy to include a shortcut function for this.
I'll add it when I get time, which is unfortunately in short supply atm.

**Comment by Tcll** [comment]
I understand the time issue, thanks for the workaround :)

**Comment by Tcll** [comment]
woops, didn't realize I'd hit close... sorry X(

**Comment by adamlwgriffiths** [comment]
I've pondered on this one for a bit.
Adding this function is a bit trickier than it looks on the surface.
Mainly because of the different data types you can use for position, orientation and scale.

For position, converting a vec3 -> vec4 requires information on what to set the W component to.
In 3D graphics you generally want w=1. But for other maths uses you want w=0 mostly.
The same goes for scale.
Rotations can also be in the form of eulers, quaternion or another matrix33/44.

So putting this into a simple function is quite messy to handle all of the possibilities.

My suggestion is to make a function in your own lib that takes the data types you are using / storing and do this conversion there.
You could also over-ride the Matrix33/44 classes and add a classmethod to do this for you.
