### ISSUE TITLE
Object Oriented Interface example NotImplementedError

### ISSUE THREAD

**Issue by mncharity** [adamlwgriffiths/Pyrr#28]
The current README.md (2014: https://github.com/adamlwgriffiths/Pyrr/blob/ababdb521e8680c8ae3ed534d771e8c3ba779d23/README.md ) Object Oriented Interface example raised a NotImplementedError in python 3.4.0.

    $ python example.py 
    Traceback (most recent call last):
      File "example.py", line 10, in <module>
        translation += [1.0, 0.0, 0.0]
      File "/bleep/venv/lib/python3.4/site-packages/pyrr/objects/base.py", line 27, in __iadd__
        self[:] = self.__add__(other)
      File "/bleep/venv/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 282, in __call__
        (self.name, str_signature(types)))
    NotImplementedError: Could not find signature for __add__: <list>
    $ python --version
    Python 3.4.0

Fyi.  Thanks for your work.

**Comment by adamlwgriffiths** [comment]
Thanks for pointing this out.
I'm going to add these verbatim to the tests.
There were a few other derps in there too.

**Comment by adamlwgriffiths** [comment]
Again, thanks for pointing this out, not good to have such glaring errors in the first project page.

I've fixed up the README examples.
-Some operations were backward (vec * mat instead of mat * vec)
-Vector4 - > Vector3 automatic conversion is no longer supported (ambiguous as to what to do with W, 3D graphics do [x/w, y/w, z/w], but other maths doesn't necessarily do this, I believe).
-Fix some other derps.

I also added support for list types for Vector3/Vector4.

If there are other valid use cases that aren't supported by the type checking, let me know.
Ie, at the moment you cannot add two quaternions together.

Also thanks for the thanks, nice to know people are getting value out of Pyrr =)
