### ISSUE TITLE
Rotating a vector by a quaternion incorrectly normalizes vector

### ISSUE THREAD

**Issue by jaycoskey** [adamlwgriffiths/Pyrr#43]
Using Python 3.5.2:
In [1]: import pyrr
In [2]: qi = pyrr.quaternion.create(1., 0., 0., 0.)
In [3]: zero = pyrr.Vector3([0., 0., 0.])
In [4]: rotated = pyrr.quaternion.apply_to_vector(qi, zero)
C:\Anaconda3\lib\site-packages\pyrr\vector.py:36: RuntimeWarning: invalid value encountered in true_divide
  return (vec.T  / np.sqrt(np.sum(vec**2,axis=-1))).T

In quaternion.py's apply_to_vector function, the nested function "apply" normalizes the input vector vec4. 
 The vector being rotated can have any magnitude, including zero.  It should not be normalized.  This was missed in the included tests because all the vectors rotated there are unit vectors.

**Comment by adamlwgriffiths** [comment]
Thanks for pointing this out. This is fixed in d89f1d24237d74c645f5243b5504f6f00aefbd28
The issue only affected zero length vectors.

There was an unnecessary normalization of the vector and after rotation a conversion back again.
This was unnecessary and has been removed.
Tests have been added.
New release on PyPi is 0.8.3.
