### ISSUE TITLE
Numpy issues with Python 3.5

### ISSUE THREAD

**Issue by adamlwgriffiths** [adamlwgriffiths/Pyrr#77]
Unit tests failing due to numpy incompatibility with python 3.5.
Ticket filed with numpy here: https://github.com/numpy/numpy/issues/11743

**Comment by foohyfooh** [comment]
From my discussion in the NumPy issue, it seems that the error is occurring because in Pyrr the equality methods currently return a single bool value while the NumPy method is expecting it to return an array of bool values.

Possible Solutions:
- Change the existing equality code to to return the array of bool from the equality comparison
- Don't use np.testing.assert_almost_equal but rather use assertTrue on the bool value returned

I prefer the first solution as it would mean better interoperability between Pyrr and NumPy, but the second solution ensures that anyone already using the library expecting a bool value doesn't have their code broken.

**Comment by foohyfooh** [comment]
I just made pull request in NumPy (https://github.com/numpy/numpy/pull/11751). If it works correctly then we shouldn't have to make any changes to the equality operators for builds to pass.

**Comment by foohyfooh** [comment]
My pull request was closed but https://github.com/numpy/numpy/pull/11756 should have fixed this issue.
We have to wait until they release 1.15.1 to know to if we can close this issue.

**Comment by foohyfooh** [comment]
NumPy released version 1.15.1. We can check if this issues can be closed if the next time a commit is made, we don't get this error again.

**Comment by foohyfooh** [comment]
I looks like the original issue with Python 3.5 is gone but there are new issues that occurs with NumPy==1.15.1

New issues:
- Python 3.3 is no longer supported. This means that in the setup.py and requirements we should be putting numpy < 1.15.0.
- We are getting equality problems in 4 tests.

**Comment by adamlwgriffiths** [comment]
Python 3.3 was pretty much abandoned a while back (https://www.python.org/dev/peps/pep-0398/#lifespan).
I think we should just drop <3.4.

Are those equality issues in 3.3? or all versions?

**Comment by adamlwgriffiths** [comment]
I've band-aided these tests to convert back to np.array before doing the comparison.
It's a shame that they've broken this as their other functions still work (np.allclose)
