### ISSUE TITLE
inverse

### ISSUE THREAD

**Issue by TimingSpace** [adamlwgriffiths/Pyrr#78]
~M is not able to get the right inverse, please check.
np.matrix(M).I get the right one

**Comment by adamlwgriffiths** [comment]
I don't have a working environment at the moment, so I cannot run the code.

We use the `np.linalg.inv` function for the inverse function.
Applying M to ~M gives the identity Matrix.
[Here is an example demonstrating this](https://repl.it/repls/BlondSubmissiveCoordinate).

Can you be more specific about what the issue is?
